language: node_js
node_js: "6"
env:
    - MASHAPEKEY='jaskdjkasjdkajskdjaksdjkasd'
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
install:
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - npm install
test:
  - npm run lint
  - npm run test
after_success: npm run coverage
