export const game = [
  { id: 16,
    name: 'Fallout: New Vegas',
    slug: 'fallout-new-vegas',
    url: 'https://www.igdb.com/games/fallout-new-vegas',
    created_at: 1297681680000,
    updated_at: 1498912254373,
    summary: 'Fallout: New Vegas is set in and around a post-apocalyptic retro-futuristic Las Vegas, following the Great War between the U.S., and China as a conventional and nuclear war that occurred on October 22 - October 23, 2077, and lasted less than two hours, while causing immense damage and destruction. Before the Great War was the Resource Wars, during which the United Nations disbanded, a plague rendered the United States paranoid, and Canada was annexed. The city of Las Vegas itself wasn\'t hit as hard as most of the other districts, with most buildings being left intact as a result. The Hoover Dam supplies free electricity and water to those who control it.',
    storyline: 'The player takes control of "the Courier", who is hired by a delivery service to take an unknown package across the Mojave Desert to "The Strip" but intercepted, shot in the head, and left for dead by a mysterious man who steals the package. After being found by a friendly local robot, Victor, and healed by a man named Doc Mitchell, the Courier is thrust back into the desert to seek revenge and recover the stolen package. Through doing this, the player becomes caught up between various factions competing for control over the desert and it\'s most valuable asset, the Hoover Dam; ultimately coming to shape the future of its inhabitants.',
    collection: 3,
    hypes: 2,
    rating: 86.9816128057632,
    popularity: 12,
    aggregated_rating: 81.9,
    aggregated_rating_count: 15,
    total_rating: 84.4408064028816,
    total_rating_count: 390,
    rating_count: 375,
    games: [ 15, 26401, 26761, 25300, 11156, 20918, 11567, 27922, 25657, 73 ],
    tags:
     [ 1,
       18,
       268435461,
       268435468,
       536870981,
       536871517,
       1073741825,
       1073741826 ],
    developers: [ 47 ],
    publishers: [ 28, 248, 2493 ],
    game_engines: [ 54, 17 ],
    category: 0,
    time_to_beat: { hastly: 126000, normally: 217068, completely: 522000 },
    player_perspectives: [ 1, 2 ],
    game_modes: [ 1 ],
    keywords: [ 69, 605 ],
    themes: [ 1, 18 ],
    genres: [ 5, 12 ],
    first_release_date: 1287446400000,
    pulse_count: 15,
    release_dates:
     [ [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object],
       [Object] ],
    alternative_names: [ [Object] ],
    screenshots: [ [Object], [Object], [Object], [Object], [Object] ],
    videos: [ [Object], [Object] ],
    cover:
     { url: '//images.igdb.com/igdb/image/upload/t_thumb/rkldlhsginkkabox1hk6.jpg',
       cloudinary_id: 'rkldlhsginkkabox1hk6',
       width: 1524,
       height: 1875 },
    esrb:
     { synopsis: 'This is an action role-playing game, set in a post-apocalyptic Mojave Desert, in which players assume the role of a survivor hero who investigates a mystery and performs a series of quests. Missions allow players to explore the Mojave Desert, surrounding casinos, and abandoned facilities; other quests involve combat with human and mutant survivors. Players use chainsaws, laser rifles, knives, and sledgehammers to kill enemies. Fighting can be frenetic and intense, highlighted by various camera effects (e.g., slow motion, blurring, screen shakes) and depictions of dismemberment, blood spray, and blood trails. In one sequence, players can choose to activate a collar bomb around a slave-woman\'s neck, resulting in depictions of blood and gore. During the course of the game, players will encounter male and female prostitutes: the screen fades to black as suggestive dialogue is heard in the background (e.g., "Nice charlies, too! Give them a shake for the Ben-man, will ya?"); there is also an extended sequence suggesting (no depiction) sexual activity with a robot (e.g., "Fisto reporting for duty . . . Please assume the position,""I suppose I should test you out . . . Servos active!" and "Something wrong with someone if they got to f**k a machine."). The storyline sometimes references a fictional drug called "chems," as well as "Day Trippers,""cracked out junkies," and "degenerate, drug-addicted killers." Players\' Character can be seen consuming the drugs, which sometimes leads to a screen-blurring effect.',
       rating: 6 },
    pegi: { rating: 5 }
  }
]
